feature: ['feature/*', 'feat/*']
fix: ['fix/*', 'hotfix/*']
docs: ['docs/*']
refactor: ['refactor/*']
test: ['test/*']
style: ['style/*']
build: ['build/*']
release: 'release/*'
dependencies: 'dependabot/*'
