name: Create Default Labels
on:
  issues:
  workflow_dispatch:
jobs:
  labels:
    name: Manage labels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DesarrolloORT/issue-label-manager-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          delete: true
