name: Build and Attach to Release

on:
  release:
    types: [published]

jobs:
  build:
    name: Build
    runs-on: windows-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Generate Environment File
        shell: powershell
        run: |
          New-Item -ItemType Directory -Path src/environments -Force
          @"
          export const environment = {
            production: true,
            RECAPTCHA_KEY_V3: "${{secrets.RECAPTCHA_KEY_V3}}",
            API_ORT_URL: "${{secrets.API_ORT_URL}}",
            API_ORT_SECURE_URL: "${{secrets.API_ORT_SECURE_URL}}"
          };
          "@ | Out-File -FilePath src/environments/environment.prod.ts -Encoding UTF8
          Copy-Item -Path src/environments/environment.prod.ts -Destination src/environments/environment.ts

      - name: Build
        run: npm run build

      - name: Compress build
        run: |
          $release_tag = $env:GITHUB_REF.Replace('refs/tags/', '')
          $zip_name = "${{secrets.REPO_NAME}}-${release_tag}.zip"
          Compress-Archive -Path dist\${{secrets.REPO_NAME}}\browser\* -DestinationPath $zip_name

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: ${{secrets.REPO_NAME}}-${{ github.event.release.tag_name }}.zip

  attach-release:
    name: Attach Build Asset to Release
    runs-on: windows-latest
    needs: build
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact

      - name: Attach build to release
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{secrets.REPO_NAME}}-${{ github.event.release.tag_name }}.zip
          asset_content_type: application/zip
