name: Publish package and attach to release

on:
  release:
    types: [published]

jobs:
  release:
    name: Publish package and attach to release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: '24'
          check-latest: true
          registry-url: 'https://npm.pkg.github.com'

      - name: Authenticate to GitHub Packages
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc
          echo "@desarrolloort:registry=https://npm.pkg.github.com" >> ~/.npmrc

      - name: Install dependencies
        run: npm install

      - name: Build library
        run: npm run build

      - name: Publish ngx-whats-new package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: dist/ngx-whats-new

      - name: Publish angularjs-whats-new package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: dist/angularjs-whats-new

      - name: Generate ngx-whats-new tarball
        run: |
          npm pack
          VERSION=$(jq -r .version package.json)
          mv desarrolloort-ngx-whats-new-$VERSION.tgz ngx-whats-new-$VERSION.tgz
        working-directory: dist/ngx-whats-new

      - name: Generate angularjs-whats-new tarball
        run: |
          npm pack
          VERSION=$(jq -r .version package.json)
          mv desarrolloort-angularjs-whats-new-$VERSION.tgz angularjs-whats-new-$VERSION.tgz
        working-directory: dist/angularjs-whats-new

      - name: Upload tarballs to release
        uses: AButler/upload-release-assets@v4.0
        with:
          files: 'dist/ngx-whats-new/*.tgz;dist/angularjs-whats-new/*.tgz'
          release-tag: ${{ github.event.release.tag_name }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
